# Generated by Django 3.0.8 on 2020-07-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200721_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About me', 'verbose_name_plural': 'About me'},
        ),
    ]
