# Generated by Django 3.0.8 on 2020-07-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200721_1720'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Skill',
        ),
    ]
